## Data Preprocessing

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df_cust = pd.read_csv('olist_customers_dataset.csv')
df_orders = pd.read_csv('olist_orders_dataset.csv')
df_order_items = pd.read_csv('olist_order_items_dataset.csv')
df_orders_payments = pd.read_csv('olist_order_payments_dataset.csv')
df_products = pd.read_csv('olist_products_dataset.csv')
df_categories = pd.read_csv('product_category_name_translation.csv')

In [4]:
# checking the data 
df_orders.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
7,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
8,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
9,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00

In [5]:
# checking for null values
df_orders.isnull().sum()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [6]:
# cleaning the data by dropping null values
df_orders = df_orders.dropna()

In [7]:
# Saved changes to the file
df_orders.to_csv('olist_orders_dataset.csv', index=False)

In [8]:
df_products.head(10)

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,arts
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sport leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,babies
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,domestic utilities
5,41d3672d4792049fa1779bb35283ed13,60.0,745.0,1.0,200.0,38.0,5.0,11.0,musical instruments
6,732bd381ad09e530fe0a5f457d81becb,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0,cool stuff
7,2548af3e6e77a690cf3eb6368e9ab61e,56.0,184.0,2.0,900.0,40.0,8.0,40.0,decoration furniture
8,37cc742be07708b53a98702e77a21a02,57.0,163.0,1.0,400.0,27.0,13.0,17.0,household appliances
9,8c92109888e8cdf9d66dc7e463025574,36.0,1156.0,1.0,600.0,17.0,10.0,12.0,toys

In [9]:
# checking for product categories names variety
df_products['product_category_name'].value_counts().head(20)

KeyError: 'product_category_name'

In [ ]:
#!pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from deep-translator) (4.13.4)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.14.1)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\adhaf\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2025.7.14)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4

In [10]:
# Transalating the product category names to English
from deep_translator import GoogleTranslator

translator = GoogleTranslator(source='pt', target='en')
cache = {}

def translate_category(name):
    if pd.isna(name):
        return name
    if name not in cache:
        readable = str(name).replace('_', ' ')
        cache[name] = translator.translate(readable)
    return cache[name]

df_products['product_category_name_english'] = df_products['product_category_name'].apply(translate_category)

KeyError: 'product_category_name'

In [11]:
df_products['product_category_name_english'].value_counts().head(20)

product_category_name_english
bed table bath                     3029
sport leisure                      2867
decoration furniture               2657
beauty health                      2444
domestic utilities                 2335
automotive                         1900
computer accessories               1639
toys                               1411
gifts watches                      1329
telephony                          1134
babies                              919
perfumery                           868
stationery shop                     849
fashion bags and accessories        849
cool stuff                          789
garden tools                        753
pet store                           719
electronics                         517
construction tools construction     400
household appliances                370
Name: count, dtype: int64

In [ ]:
# Dropped the original category name column
df_products = df_products.drop(columns=['product_category_name'])
df_products.head(10)

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,arts
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sport leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,babies
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,domestic utilities
5,41d3672d4792049fa1779bb35283ed13,60.0,745.0,1.0,200.0,38.0,5.0,11.0,musical instruments
6,732bd381ad09e530fe0a5f457d81becb,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0,cool stuff
7,2548af3e6e77a690cf3eb6368e9ab61e,56.0,184.0,2.0,900.0,40.0,8.0,40.0,decoration furniture
8,37cc742be07708b53a98702e77a21a02,57.0,163.0,1.0,400.0,27.0,13.0,17.0,household appliances
9,8c92109888e8cdf9d66dc7e463025574,36.0,1156.0,1.0,600.0,17.0,10.0,12.0,toys

In [15]:
# checking for null values
df_products.isnull().sum()

product_id                       0
product_name_lenght              0
product_description_lenght       0
product_photos_qty               0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
product_category_name_english    0
dtype: int64

In [14]:
# dropping null values
df_products = df_products.dropna()

In [16]:
# Saved changes to the file
df_products.to_csv('olist_products_dataset.csv', index=False)